### ISSUE TITLE
Extend to include flatpack

### ISSUE THREAD

**Issue by GeorgelPreput** [dnut/upgrade#2]
Could this script be extended to also update Flatpack packages, if flatpack is installed?

**Comment by dnut** [comment]
It is doable. I've already been considering what would be the best way to do it, since I'd like to automate my own flatpak updates.

One approach could simply be to add a flatpak option into the config file that defaults to false. The script can easily check that value, and then run `flatpak update` if it is set to true. That would handle system-installed packages pretty easily. Upgrading user-installed packages is also doable but would require more code and configuration.

I'm also considering other approaches to make this more generic so users have complete control of exactly what this runs. One option would be to let users define custom commands in the config file. Another option would be to support topgrade as a backend, which already has a lot of tooling and customizability to support upgrading all different kinds of packages. But topgrade isn't designed for upgrading without user interaction, so I'm not sure if that's a great option.

**Comment by dnut** [comment]
I just committed a basic implementation to support this. I'll be testing it on some of my machines for a bit before I push it to the AUR.

**Comment by GeorgelPreput** [comment]
Used it from source (uninstalled the AUR version first) and it works very nicely, at least for my system. Thanks!

**Comment by dnut** [comment]
@GeorgelPreput 

That first commit had some bugs. I fixed those bugs and released 0.3.0. You can install it from the AUR to get the latest version including the fixes.

**Comment by GeorgelPreput** [comment]
Great, thank you!
I'll give it a try tonight
